/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Program */

#ifndef _Included_Program
#define _Included_Program
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Program
 * Method:    getGreetingMessageNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Program_getGreetingMessageNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
